### ISSUE TITLE
Not retrieving more than 20 zones

### ISSUE THREAD

**Issue by lalgarvi-te** [linuxhq/ansible-collection-cloudflare#1] opened 2023-12-27 05:20 UTC
Hello,
It seems the zone role isn't retrieving or processing more than 20 zones.
Any additional zones (in alpha order i believe) after number 20 will not be present on `TASK [linuxhq.cloudflare.zone : Ensure dictionary of zone ids generated] ` 
It seems to copy the behavior on CF zone page; it lists by sets of 20 zones into each page.
Regards

**Comment by tkimball83** [comment] 2023-12-27 05:34
Unfortunately I don't have an account with more than 20 zones to test this.  

However, can you test this commit and update your inventory to override the new default variables?

https://github.com/linuxhq/ansible-collection-cloudflare/commit/968a71731301805597d2027a8130fe49a23eebc4

**Comment by lpalgarvio** [comment] 2024-01-31 02:27
heya, sorry for the long wait.
i'm continuing on this with my personal account instead of my work account, where i opened this by accident.

@ accounts
i looked this up on the docs https://developers.cloudflare.com/api/operations/zones-get
pagination is mentioned and that only 20 results at a time are returned by default.
the same applies when you look on cloudflare UI.

@ patch
i was actually going to supply today a quick dirty patch to overcome the issue partially.

```
diff -Nru ansible-collection-cloudflare/roles/zone/tasks/main.yml collections/galaxy/ansible_collections/linuxhq/cloudflare/roles/zone/tasks/main.yml
--- ansible-collection-cloudflare/roles/zone/tasks/main.yml     2024-01-31 02:26:23.632620954 +0000
+++ collections/galaxy/ansible_collections/linuxhq/cloudflare/roles/zone/tasks/main.yml 2024-01-23 06:41:23.497966000 +0000
@@ -9,7 +9,7 @@
     method: GET
     status_code:
       - 200
-    url: 'https://api.cloudflare.com/client/v4/zones'
+    url: 'https://api.cloudflare.com/client/v4/zones?per_page=50&page=1'
   register: _zones
   when:
     - cf_auth_token is not none
diff -Nru ansible-collection-cloudflare/roles/zone_info/tasks/main.yml collections/galaxy/ansible_collections/linuxhq/cloudflare/roles/zone_info/tasks/main.yml
--- ansible-collection-cloudflare/roles/zone_info/tasks/main.yml        2024-01-31 02:23:38.886161871 +0000
+++ collections/galaxy/ansible_collections/linuxhq/cloudflare/roles/zone_info/tasks/main.yml    2024-01-23 06:40:39.353450994 +0000
@@ -11,7 +11,7 @@
       - 200
       - 401
       - 403
-    url: 'https://api.cloudflare.com/client/v4/zones'
+    url: 'https://api.cloudflare.com/client/v4/zones?per_page=50&page=1'
   register: _zones
   when:
     - cf_auth_token is not none
```

i'm going to test your code and then add a patch on top because i found out that 2 files needed to me modified.

**Comment by tkimball83** [comment] 2024-01-31 02:30
I was planning to update both roles once confirmed the override of the role defaults worked on your end.  Let me know, thanks!

**Comment by lpalgarvio** [comment] 2024-01-31 02:45
confirmed working with both roles changed

**Comment by lpalgarvio** [comment] 2024-01-31 02:59
thanks!

**Comment by tkimball83** [comment] 2024-01-31 03:00
Release https://github.com/linuxhq/ansible-collection-cloudflare/releases/tag/v1.1.8 is now available with changes to both roles.  Thanks for pointing out the issue, much appreciated!

Closing issue.

**Closed by tkimball83** 2024-01-31 03:00 UTC
